### ISSUE TITLE
Kleurcodes op de web weergave?

### ISSUE THREAD

**Issue by alexhebing** [ProDemos/pds#114]
Wat mooi zou zijn: als de kleurcodes (ik denk hex) terug te vinden zouden zijn op pds.prodemos.nl. Is dat denkbaar @commonpike ?

**Comment by commonpike** [comment]
ja, dat kan. 

De hele bedoeling is eigenlijk dat je ze niet gebruikt, maar dat je bv
`var(--pds-color-blue-80);` gebruikt. Die kleuren veranderen namelijk soms.
Ze zijn veranderd in de afgelopen jaren.

Onder 'resources' heb je het sketch file, dat is feitelijk de documentatie, en daar staan de hex kleuren ook in.
Maar ik kan ze ook op de pagina tonen ergens.

**Comment by alexhebing** [comment]
Oh ja, ok. Nee, die link naar Sketch is voldoende. Thanks!
