### ISSUE TITLE
List of changes to discuss

### ISSUE THREAD

**Issue by sdevogel** [ProDemos/pds#26]
# Sander's List
- [ ] Color blue should be changed to new blue `#007fa2` 
- [ ] Consider using CSS variables instead of SCSS variables to simplify compiled css (css variables can be updated at runtime instead of bakked in when compiling)
- [ ] Consider using REM for type sizes (based on HTML element font size for accessibility and coherent sizes)
- [ ] Color text > pure black not gray
- [ ] Missing icons: Search, location, help-circle, clock, home, backpack, download
- [ ] Hambuger icon (3 stripes) conflicting with hamburger icon (real hamburger)
- [ ] Update logo (without color bg)
- [ ] Define browsersupport
- [ ] Define accessibility rules / guidelines

## Questions I had during development
- Default type settings, where are they defined? I can only find type settings defined in scopes

**Comment by commonpike** [comment]
# Pikes list 
## missing items
- [ ] bw logo as in sketch file / footer
- [ ] regular pds-c-menu with chevron as in sketch file
- [ ] base
  - [ ] fira-sans-semibold (weight 600)
- [ ] helpers
  - [ ] @pds-media(breakpoint,min|max) helper (replacing `media-until`,`media-between` and `media-from`)
- [ ] form elements
  - [ ] type=date, type=time
  - [ ] textarea.pds-c-input
  - [ ] label.pds-c-input (for radio/checkboxes)
  - [ ] html5 form validation on hidden radio/check buttons - input elements have to be visible , 1x1 px
  - [ ] readonly elements
  - [ ] override disabled styling for themed elements
  - [ ] .pds-c-progress.white .spinner
- [ ] icons
  - [ ] plus, plus-circled
  - [ ] alert, alert-circled
  - [ ] dots, dots-cirlced
  - [ ] question, question-circled
  - [ ] check-plain
  - [ ] error-plain
  - [ ] arrow-upright
  - [ ] eye, eye-crossed 
 ## missing documentation
- [ ] logo with .slant dropdown shadow 
## rethink variables 
- [ ] font-sizes 
- [ ] line-heights
- [ ] breakpoints

**Comment by commonpike** [comment]
> Default type settings, where are they defined? I can only find type settings defined in scopes

There aren't any. I (we?) thought it was best if the designer defined his own base font sizes in their own design - ofcourse using the pds-fontsize(); helper. Otherwise, a designer would have to override all the definitions for h1,h2,a,li etc just to get the base design up.

Unless they use a 'scope', iow wrap the content to be styled in in a `pds-s-bla` scope and knowingly accept all the styles in that scope. However... I never used the only scope we ever defined.

**Comment by commonpike** [comment]
Here's an example of how I overridden PDS defaults in my app - which, ideally, you should not have to do .. 

```
// --------------------
// overide pds
// --------------------

$pds-deftheme: "public";

/*
    $pds-fontsizes: (
        tiny: 8px,
        xxs: 12px,
        xs: 14px,
        s: 16px,
        default: 18px,
        m: 22px,
        l: 24px,
        xl: 32px,
        xxl: 44px,
        huge: 56px,
    );
*/

$pds-fontsizes: map.set($pds-fontsizes, l, 28px);
$pds-fontsizes: map.set($pds-fontsizes, mob-l, 24px);
$pds-fontsizes: map.set($pds-fontsizes, xl, 38px);
$pds-fontsizes: map.set($pds-fontsizes, mob-xl, 32px);
$pds-fontsizes: map.set($pds-fontsizes, xxl, 48px);

/*
    $pds-lineheights: (
        none: 0,
        xs: 1,
        s: 1.25,
        default: 1.5,
        m: 1.75,
    );

*/

/*
    $pds-breakpoints: (
        xs: 0,
        sm: 550px,
        md: 768px,
        lg: 990px,
        xl: 1200px
    );
*/

$pds-breakpoints: map.set($pds-breakpoints, phone-small, 375px);
$pds-breakpoints: map.set($pds-breakpoints, phone, 400px);
$pds-breakpoints: map.set($pds-breakpoints, phone-wide, 480px);
$pds-breakpoints: map.set($pds-breakpoints, phablet, 560px);
$pds-breakpoints: map.set($pds-breakpoints, tablet-small, 640px);
$pds-breakpoints: map.set($pds-breakpoints, tablet, 768px);
$pds-breakpoints: map.set($pds-breakpoints, tablet-wide, 1024px);
$pds-breakpoints: map.set($pds-breakpoints, desktop, 1248px);
$pds-breakpoints: map.set($pds-breakpoints, desktop-wide, 1500px);
$pds-breakpoints: map.set($pds-breakpoints, desktop-large, 2000px);
```

**Comment by sdevogel** [comment]
icons maybe via https://lucide.dev/icon/align-justify?query=

**Comment by commonpike** [comment]
I've moved all items here into seperate issues - @sdevogel , can we close this issue ?

**Comment by sdevogel** [comment]
yess I think so 👍
