### ISSUE TITLE
Add new icons

### ISSUE THREAD

**Issue by commonpike** [ProDemos/pds#34]
Add icons for 
  - [x] Search, 
  - [x] location, 
  - [x] help-circle, 
  - [x] clock, 
  - [x] home, 
  - [x] backpack, 
  - [ ] download
  - [x] plus, plus-circled
  - [x] alert, alert-circled
  - [x] dots, dots-circled
  - [x] question, question-circled
  - [x] check-plain
  - [x] error-plain
  - [x] arrow-upright
  - [x] eye, eye-crossed 

Also, tweak the svg in sketch so they are the same in linewidth etc.

**Comment by commonpike** [comment]
@sdevogel - I think the name should reflect what is depicted, not what it is used for - so not `search`, but `magnifying-glass` and not `help` but `question-mark`

**Comment by sdevogel** [comment]
agreed!

**Comment by commonpike** [comment]
sanders icons are in the sketch file

**Comment by commonpike** [comment]
pike mails svg to sander first
