### ISSUE TITLE
Fix hamburger bug

### ISSUE THREAD

**Issue by commonpike** [ProDemos/pds#36]
Hambuger icon (3 stripes) conflicting with hamburger icon (real hamburger) - they have the same name in css

**Comment by commonpike** [comment]
@sdevogel - I never used the hamburger, because I have a open/closed state - should we not use that instead ?

**Comment by sdevogel** [comment]
I use it on the prodemos website. not sure what you mean with open/close state...

**Comment by commonpike** [comment]
moved the 'other' hamburger to graphics, so it wont conflict anymore
