### ISSUE TITLE
Document browsersupport / accessibility rules

### ISSUE THREAD

**Issue by commonpike** [ProDemos/pds#41]
- [x] Define browsersupport
- [x] Define accessibility rules / guidelines

**Comment by commonpike** [comment]
@commonpike : add page to pds.prodemos.nl

**Comment by sdevogel** [comment]
# PDS Browsersupport

The following browsers should be supported and should be tested against. 
- 

## Browserlist
Use the following snippet in package.json to prefix/compile to support these browsers:

```javascript
"browserslist": [ 
    "last 2 versions"
]
```

**Comment by sdevogel** [comment]
@alexhebing could you check what the browsers versions are on a couple of websites so we can define the browsers to support?
