### ISSUE TITLE
Update sketch file in repo

### ISSUE THREAD

**Issue by commonpike** [ProDemos/pds#42]
This file is from Zicht, and very old and misleading - we agreed to put a minimal new version there.

**Comment by commonpike** [comment]
Online file op sketch.com, in ProDemos workspace

**Comment by sdevogel** [comment]
Ik heb een workspace aangemaakt en de PDS library toegevoegd. 
De link hiernaar is: https://www.sketch.com/s/a038cf33-0b70-4241-8eb1-e07871617039

Dit document kan middels de link door iedereen worden bekeken en gedownload worden. Omdat het een library is kun je deze ook toevoegen aan ander document en de componenten eruit gebruiken. Zodra er an een aanpassen is aan een van de componenten krijgt de gebruiker hier een melding van in zijn eigen document als hij deze heeft toegevoegd. Dit kun je doen door rechts boven op de 3 puntjes de klikken en vervolgens op 'add library'. Ik ben nu de admin van dit document en kan aanpassingen maken, de rest alleen bekijken, downloaden en commenten.

<img width="311" alt="Screenshot 2023-05-30 at 08 12 10" src="https://github.com/ProDemos/pds/assets/31384992/f7332c92-e582-4f29-a2ff-d345d749d709">

@commonpike kun jij deze link toevoegen aan PDS? Ik snap nog niet hemelaal hoe dat werkt met de tekst documenten in PDS...
