### ISSUE TITLE
Create favicons in several colors

### ISSUE THREAD

**Issue by alexhebing** [ProDemos/pds#46]
Eentje van Nick, al besproken met @sdevogel :

Het lijkt me goed als we voor de verschillende prodemos sites verschillende kleuren favicons gebruiken. Zou jij voor de verschillende huisstijl kleuren een favicon setje willen renderen? Ik zie voor me dat het gewoon de M is in de verschillende kleuren (geen achtergrond). Wellicht ook goed om als asset toe te voegen aan de PDS site.

**Comment by commonpike** [comment]
Duplicate of https://github.com/ProDemos/pds/issues/47
