### ISSUE TITLE
use github pages for hosting ?

### ISSUE THREAD

**Issue by commonpike** [ProDemos/pds#9]
We can use github pages for hosting:

![Screenshot 2020-10-29 at 22 16 25](https://user-images.githubusercontent.com/3535798/97633507-7cd6b700-1a34-11eb-9cee-fbb5315b7fa6.png)

We could currently host the demo/html folder of the master branch, but that will probably break soon due to that symlink.
Problem is, the repo is private. But this was public too

https://designsystem.prodemos.nl/

there's nothing to hide here, and I don't know why there would ever be ?

**Comment by alexhebing** [comment]
Also, the repo is no longer private.
